import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
print("......................")
y=np.array([[7,8],[9,10],[11,12]])
print(y)
print("......................")
#print(x+y)
#print(x-y)
print(x*y)